language: ruby
os: linux
distr: xenial
cache: bundler
before_install: gem install bundler
script: bundle exec rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.10
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: 2.5.8
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: 2.6.6
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: 2.7.1
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: ruby-head
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: jruby-head
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: truffleruby
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true FULL_TEST_COVERAGE_CHECK=true
  - rvm: 2.4.10
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.5.8
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.6.6
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.7.1
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: truffleruby
    gemfile: gemfiles/without_external_deps.gemfile
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: truffleruby
