language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.9
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: 2.5.7
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: 2.6.5
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: 2.7.0
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: ruby-head
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: jruby-head
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: truffleruby
    gemfile: gemfiles/with_external_deps.gemfile
    env: TEST_PLUGINS=true
  - rvm: 2.4.9
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.5.7
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.6.5
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/without_external_deps.gemfile
  - rvm: truffleruby
    gemfile: gemfiles/without_external_deps.gemfile
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: truffleruby
sudo: false
cache: bundler
before_install: gem install bundler
script: bundle exec rspec
