name: Build
on: [push]
jobs:
  full-check:
    runs-on: ubuntu-latest
  env:
    FULL_COVERAGE_CHECK: true
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: (Linter) Rubocop
        run: bundle exec rubocop
      - name: (Test) RSpec (with plugin tests)
        run: bin/rspec -w
      - name: (Test) RSpec (without plugin tests)
        run: bin/rspec -n
  specs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    env:
      FULL_COVERAGE_CHECK: false
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        experimental: [false]
        include:
          - ruby: head
            experimental: true
          - ruby: jruby
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Specs (with dependencies)
        run: bin/rspec -w
      - name: Run Specs (without dependencies)
        run: bin/rspec -n
