name: Build
on: [push]
jobs:
  mainstream-ruby-full-check:
    runs-on: ubuntu-latest
    env:
      FULL_COVERAGE_CHECK: true
      TEST_PLUGINS: true
      FULL_TEST_COVERAGE_CHECK: true
      BUNDLE_GEMFILE: gemfiles/with_external_deps.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: (Bundler) Install dependencies
        run: bundle install
      - name: (Rubocop) Check for codestyle
        run: bundle exec rake rubocop
      - name: (RSpec) Tests
        run: bundle exec rake rspec
  specs-on-relevant-rubies:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    env:
      FULL_COVERAGE_CHECK: false
      TEST_PLUGINS: true
      FULL_TEST_COVERAGE_CHECK: true
      BUNDLE_GEMFILE: gemfiles/with_external_deps.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        experimental: [false]
        include:
          - ruby: head
            experimental: true
          - ruby: truffleruby
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: (Bundler) Install dependencies
        run: bundle install
      - name: (RSpec) Tests
        run: bundle exec rake rspec
