name: Build

on: [push, pull_request]

env:
  FULL_COVERAGE_CHECK: true

jobs:
  full-check:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '0exp/qonfig'

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Run Linter
        run: bundle exec ci-helper RubocopLint
      - name: Check missed spec suffixes
        run: bundle exec ci-helper CheckSpecSuffixes --extra-paths spec/*.rb --ignored-paths spec/*_helper.rb spec/**/*_examples.rb
      - name: Run Specs (with dependencies)
        run: bin/rspec -w
      - name: Run Specs (without dependencies)
        run: bin/rspec -n
      - name: Audit
        run: bundle exec ci-helper BundlerAudit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    env:
      FULL_COVERAGE_CHECK: false

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '0exp/qonfig'

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2", "3.3"]
        experimental: [false]
        include:
          - ruby: head
            experimental: true
          - ruby: jruby
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run Specs (with dependencies)
        run: bin/rspec -w
      - name: Run Specs (without dependencies)
        run: bin/rspec -n
