name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  FULL_TEST_COVERAGE_CHECK: true
  TEST_PLUGINS: true
  BUNDLE_GEMFILE: gemfiles/with_external_deps.gemfile

jobs:
  full-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Run Linter
        run: bundle exec rubocop || true
      - name: Run specs
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec
